name: 🐞 Bug report
description: Something reproducible that is broken and should be fixed.
title: "[Bug]: <short description>"
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping make Synack better!  
        **Usage/how-to questions will be closed**—please use Discussions or StackOverflow instead.

  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-flight
      description: Please confirm the following.
      options:
        - label: I have searched existing issues and Discussions.
          required: true
        - label: This is **not** a usage/how-to question.
          required: true
        - label: I have read the contribution guidelines.
          required: true

  - type: input
    id: synack-version
    attributes:
      label: Synack version
      placeholder: e.g., 0.4.2 or commit SHA
    validations:
      required: true

  - type: input
    id: dotnet-version
    attributes:
      label: .NET SDK/runtime version
      placeholder: e.g., .NET 8.0.8 SDK 8.0.400
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS and version
      placeholder: e.g., Windows 11 24H2 / Ubuntu 24.04 / macOS 14.6
    validations:
      required: true

  - type: textarea
    id: other-stack
    attributes:
      label: Related tooling / libraries
      description: If relevant, include DI container, logging framework, IDE, reverse proxy, etc.
      placeholder: e.g., Microsoft.Extensions.DependencyInjection 8.0.0, Serilog 3.1, Rider 2024.2

  - type: textarea
    id: repro
    attributes:
      label: Minimal reproducible example
      description: Provide the **smallest possible** code/config to reproduce. Link to a repo or include inline code.
      render: csharp
      placeholder: |
        // minimal Program.cs or test demonstrating the issue
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happens?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs/stack traces
      description: Redact secrets. Use backticks for code fences.
      render: text

  - type: checkboxes
    id: regression
    attributes:
      label: Regression?
      options:
        - label: This worked in a previous Synack version
        - label: I can bisect to a specific commit

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / recordings (optional)

  - type: checkboxes
    id: ack
    attributes:
      label: Acknowledgements
      options:
        - label: I understand that maintainers may label **more-information-needed** and close after ~30 days without response.
          required: true
